services:
  ubuntu:
    hostname: box
    build: .
    tty: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /sys:/sys:ro
      - /var/lib/docker/user-data:/home/user-data:rw
    restart: always

#    cgroupns_mode: host
    privileged: true
#    pre_build_image: true
    cap_add:
      - SYS_ADMIN
    container_name: maib
    ports:
      - 80:80
      - 443:443
      - 993:993
      - 995:995
      - 25:25
      - 465:465
      - 587:587
      - 4190:4190 
      - 53:53
      - 10025:10025
